-- SELECT 내 IF 조건
SELECT WAREHOUSE_ID
    , WAREHOUSE_NAME
    , ADDRESS
    , CASE WHEN FREEZER_YN is null THEN 'N'
        ELSE FREEZER_YN
        END AS FREEZER_YN
FROM FOOD_WAREHOUSE 
WHERE WAREHOUSE_NAME LIKE '%경기%'
ORDER BY WAREHOUSE_ID



-- NVL로 대체
-- SELECT 내 IF 조건
SELECT WAREHOUSE_ID
    , WAREHOUSE_NAME
    , ADDRESS
    , NVL(FREEZER_YN, 'N') 
FROM FOOD_WAREHOUSE 
WHERE WAREHOUSE_NAME LIKE '%경기%'
ORDER BY WAREHOUSE_ID
