-- gender: null / 0 = 남 / 1 = 여
-- gender <> null 
-- 년 / 월 / 성별 회원수 | 년, 월, 성별 ASC


-- 한 사람(성별)이 같은 년, 월에 여러 상품을 주문했을 수 있다. -> ID를 COUNT해야 함 (DISTINCT!)

-- 1. 정답
SELECT TO_CHAR(O.SALES_DATE, 'YYYY') YEAR, 
       TO_CHAR(O.SALES_DATE, 'MM')*1 MONTH, 
       GENDER, 
       COUNT(DISTINCT O.USER_ID) USERS
FROM USER_INFO U
INNER JOIN ONLINE_SALE O
ON U.USER_ID = O.USER_ID
WHERE U.GENDER IS NOT NULL
GROUP BY TO_CHAR(O.SALES_DATE, 'YYYY'), TO_CHAR(O.SALES_DATE, 'MM'), U.GENDER
ORDER BY 1, 2, 3



-- 2. EXTRACT 사용: DATE에서 특정 정보 추출
-- YEAR , MONTH , DAY , HOUR , MINUTE , SECOND
SELECT EXTRACT(YEAR FROM O.SALES_DATE) YEAR, 
       EXTRACT(MONTH FROM O.SALES_DATE)*1 MONTH, 
       GENDER, 
       COUNT(DISTINCT O.USER_ID) USERS
FROM USER_INFO U
INNER JOIN ONLINE_SALE O
ON U.USER_ID = O.USER_ID
WHERE U.GENDER IS NOT NULL
GROUP BY EXTRACT(YEAR FROM O.SALES_DATE), EXTRACT(MONTH FROM O.SALES_DATE), U.GENDER
ORDER BY 1, 2, 3