-- 202208 ~ 202212, 대여 횟수 5회 이상
-- 월별, 자동차 ID 별 / 총 대여횟수 / 월 ASC, 자동차ID DESC
-- 대여 횟수 = 0 제외


-- 1. 오답
-- ORDER가 안됨
-- RDCORDS = 0인 경우 어떻게 제외?
SELECT TO_CHAR(START_DATE, 'FMMM') MONTH, CAR_ID, COUNT(*) RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE CAR_ID IN 
(SELECT CAR_ID
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY CAR_ID 
HAVING COUNT(*) >= 5)
GROUP BY TO_CHAR(START_DATE, 'FMMM'), CAR_ID
ORDER BY MONTH DESC --, CAR_ID DESC



2. 정답
-- 범위 => BETWEEN 사용
-- HAVING에 ALIAS 사용 불가
SELECT TO_CHAR(START_DATE, 'MM')*1 MONTH, CAR_ID, COUNT(*) RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE TO_CHAR(START_DATE,'YYYYMM') BETWEEN '202208' AND '202210'
      AND CAR_ID IN (SELECT CAR_ID
                    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
                    WHERE TO_CHAR(START_DATE,'YYYYMM') BETWEEN '202208' AND '202210'
                    GROUP BY CAR_ID 
                    HAVING COUNT(*) >= 5)
GROUP BY TO_CHAR(START_DATE, 'MM'), CAR_ID
HAVING COUNT(*) != 0
ORDER BY 1 ASC, 2 DESC
