-- 게시판tb, 첨부파일tb
-- WRITER_ID = USER_ID
-- 거래 완료 / 금액 >= 70 / 총거래금액 순
-- 한 아이디 당 여러개 물건?
-- GROUP > HAVING


-- 1. 오답
SELECT B.USER_ID, B.NICKNAME, SUM(A.PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD A
INNER JOIN USED_GOODS_USER B
ON A.WRITER_ID = B.USER_ID
WHERE A.STATUS = 'DONE'
GROUP BY B.USER_ID, B.NICKNAME
HAVING SUM(A.PRICE) > 700000
ORDER BY TOTAL_SALES



-- 2. 오답
SELECT USER_ID, NICKNAME, SUM(PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD A
INNER JOIN USED_GOODS_USER B
ON A.WRITER_ID = B.USER_ID
WHERE A.STATUS = 'DONE'
AND SUM(PRICE) >= 700000    -- GROUP 되기 전에 집계함수 조건식을 넣어서 틀림
GROUP BY USER_ID, NICKNAME  


-- 3. 정답
SELECT USER_ID, NICKNAME, SUM(PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD A
INNER JOIN USED_GOODS_USER B
ON A.WRITER_ID = B.USER_ID
WHERE A.STATUS = 'DONE'
GROUP BY USER_ID, NICKNAME      -- GROUP BY 사용 시, 집계함수 외 SELECT 절의 모든 컬럼 포함?
HAVING SUM(A.PRICE) >= 700000   -- 집계함수의 조건식은 HAVING으로..
ORDER BY TOTAL_SALES

SELECT USER_ID, NICKNAME, SUM(PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD A
INNER JOIN USED_GOODS_USER B
ON A.WRITER_ID = B.USER_ID
WHERE A.STATUS = 'DONE'
GROUP BY USER_ID, NICKNAME  
HAVING SUM(PRICE) >= 700000    
ORDER BY 3