-- 식당 정보
-- 음식 종류 별, 즐겨찾기 가장 많은 / 음식 종류 순


-- 1. 오답
SELECT FOOD_TYPE, MAX(FAVORITES)
FROM REST_INFO
GROUP BY FOOD_TYPE
-- 여기서 REST_ID, REST_NAME 이 정보를 어떻게 끌고와야 할지 모르겠다...



-- 2. 정답

-- 2.1
SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
FROM REST_INFO
WHERE (FOOD_TYPE, FAVORITES) IN (
SELECT FOOD_TYPE, MAX(FAVORITES)
FROM REST_INFO
GROUP BY FOOD_TYPE      -- 여기서 필요하 요소는 필터링이 끝남, 이 값을 기준으로 나머지 컬럼 값을 찾으면 됨
)
ORDER BY FOOD_TYPE DESC


-- 2.2 join 사용 (처음 생각한 방식이랑 유사... 근데 1번이 더 좋을 듯)
SELECT a.FOOD_TYPE, a.REST_ID , a.REST_NAME, a.FAVORITES
FROM REST_INFO a 
INNER JOIN (SELECT FOOD_TYPE , MAX(FAVORITES) AS MAXF
            FROM REST_INFO  
            GROUP BY FOOD_TYPE) b 
ON a.FOOD_TYPE = b.FOOD_TYPE AND a.FAVORITES = b.MAXF
ORDER BY a.food_type DESC;



-- 2.3 PARTITION BY
-- PARTITION BY FOOD_TYPE 구문은 FOOD_TYPE을 기준으로 그룹화
-- FOOD_TYPE 그룹 내에서 FAVORITES를 기준으로 내림차순으로 정렬한 후에 각 행에 일련번호(RN)를 할당합니다. 

SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
FROM (
SELECT  ROW_NUMBER() OVER(PARTITION BY FOOD_TYPE ORDER BY FAVORITES DESC) RN, A.*
FROM REST_INFO A
)
WHERE RN = 1
ORDER BY FOOD_TYPE DESC


