-- 도서, 판매정보
-- 22년 1월 / 카테고리 별 도서 판매량 / 카테고리명순


SELECT CATEGORY, SUM(SALES) AS TOTAL_SALES
FROM BOOK A
INNER JOIN BOOK_SALES B
ON A.BOOK_ID = B.BOOK_ID
WHERE TO_CHAR(SALES_DATE, 'YYYYMMDD') LIKE '202201%'
GROUP BY CATEGORY
ORDER BY CATEGORY
