-- 1. MAX or <>MAX
-- 2. <>MAX -> MIN ?

SELECT HACKER_ID, NAME, CNT
FROM
(
SELECT H.HACKER_ID, H.NAME, COUNT(CHALLENGE_ID) AS CNT
  FROM HACKERS H,  CHALLENGES C
WHERE H.HACKER_ID = C.HACKER_ID
GROUP  BY H.HACKER_ID, H.NAME
)  A,
(
SELECT MAX(COUNT(*)) AS MAX_CNT
  FROM CHALLENGES C
GROUP BY C.HACKER_ID
) B
WHERE CNT = MAX_CNT
UNION
SELECT MIN(HACKER_ID) AS HACKER_ID, MIN(NAME) AS NAME, CNT
FROM
(
SELECT H.HACKER_ID, H.NAME, COUNT(CHALLENGE_ID) AS CNT
  FROM HACKERS H,  CHALLENGES C
WHERE H.HACKER_ID = C.HACKER_ID
GROUP  BY H.HACKER_ID, H.NAME
)  A,
(
SELECT MAX(COUNT(*)) AS MAX_CNT
  FROM CHALLENGES C
GROUP BY C.HACKER_ID
) B
GROUP BY MAX_CNT, CNT
HAVING COUNT(*) = 1 AND CNT != MAX_CNT
ORDER BY 3 DESC, 1;
