-- 차집합

/* check
sql 절차 중요!
order를 먼저 적용하려면 -> 1. 서브쿼리 / 2. fetch ..
*/


-- 1. 전체 서브쿼리 사용
SELECT NAME, DATETIME 
FROM (SELECT A.NAME, A.DATETIME
    FROM ANIMAL_INS A 
    WHERE NOT EXISTS (
        SELECT * 
        FROM ANIMAL_OUTS B
        WHERE A.ANIMAL_ID = B.ANIMAL_ID) 
    ORDER BY DATETIME)
WHERE ROWNUM <= 3


-- 2. fetch  사용
SELECT NAME,DATETIME
    FROM ANIMAL_INS
    WHERE ANIMAL_ID NOT IN (SELECT ANIMAL_ID FROM ANIMAL_OUTS)
    ORDER BY DATETIME FETCH FIRST 3 ROWS ONLY;



-- join 사용
SELECT A.NAME, A.DATETIME 
FROM ANIMAL_INS A
LEFT JOIN ANIMAL_OUTS B
ON A.ANIMAL_ID = B.ANIMAL_ID
WHERE B.ANIMAL_ID IS NULL
ORDER BY 2      -- 2 = 2번째 컬럼
FETCH FIRST 3 ROWS ONLY;


-- NOT IN 사용

2
3
4
SELECT NAME, DATETIME
FROM ANIMAL_INS
WHERE ANIMAL_ID NOT IN (SELECT ANIMAL_ID FROM ANIMAL_OUTS)
ORDER BY DATETIME 
FETCH FIRST 3 ROWS ONLY;