-- 22/4/13 취소되지 않은, CS / 예약일시 ASC
-- JOIN: PT_NO = PT_NO / MDDR_ID = DR_ID	

-- 22/4/13일 예약된 CS 진료 내역을 구하라

SELECT A.APNT_NO, P.PT_NAME, P.PT_NO, A.MCDP_CD, D.DR_NAME, A.APNT_YMD
FROM APPOINTMENT A
INNER JOIN DOCTOR D
ON A.MDDR_ID = D.DR_ID
INNER JOIN PATIENT P
ON A.PT_NO = P.PT_NO
WHERE TO_CHAR(A.APNT_YMD, 'YYYYMMDD') = '20220413'
      AND A.MCDP_CD = 'CS'
      AND A.APNT_CNCL_YN = 'N'
ORDER BY 6

